### ISSUE TITLE
Move fluentd and metricbeat services to candhis_network

### ISSUE THREAD

**Issue by tul1** [tul1/candhis_api#5]
Don't forget to update the configurations of metricbeat and fluentd.

Metricbeat:
```
output.elasticsearch:
  hosts: ["http://localhost:9201"]

setup.kibana:
  hosts: ["http://localhost:5601"]
```

Fluentd:
```
  fluentd:
    build:
      context: ./infra/fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    environment:
      FLUENT_ELASTICSEARCH_HOST: localhost
      FLUENT_ELASTICSEARCH_PORT: 9201
    volumes:
      - ./infra/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - /var/log/journal:/var/log/journal
    networks:
      - logs_network
    depends_on:
      elasticsearch_logs:
        condition: service_healthy
```
